url: "https://etive.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: "etive.io" # the name of your site
description: "Making gravitational-wave analysis fun, easy, and reproducible"
email: contact@etive.io

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  tutorials:
    output: true
    permalink: /tutorials/:title/
  plugins:
    output: true
    permalink: /plugins/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - README.md
